spring.data.mongodb.uri=${MONGO_URL}
spring.data.mongodb.database=meetry

spring.data.redis.url=${REDIS_URL}

#prod
cookie.domain=meetry-app.vercel.app/

#local
#cookie.domain=localhost

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.codec.max-in-memory-size=2MB

## Email Configuration
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.username=email@email.com
#spring.mail.password=password
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.connectiontimeout=5000
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.writetimeout=5000